README.md, WORKSPACE, third_party/repositories.bzl
Allows for external projects to add trellis dependencies along with trellis.
=> Allow projects to injest trellis third_party dependencies

trellis/core/publisher.hpp, trellis/tools/trellis-cli/topic_main.cpp
Now when using `trellis-cli topic publish` the tool will retrieve the metadata for the topic from any subscribers whom are online. This allows the tool to dynamically construct proto messages with the appropriate schema dynamically.
=> Trellis CLI Dynamic Publisher

trellis/core/logging.hpp, trellis/core/node.cpp, trellis/examples/logger/BUILD, trellis/examples/logger/main.cpp
Allow `trellis::core::Log` to be used standalone
=> Standalone Logging APIs

trellis/core/message_consumer.hpp, trellis/core/test/test_message_consumer.cpp, trellis/examples/subscriber/app.cpp, trellis/examples/subscriber/app.hpp
In some cases it may be nice to know which topic your inbound message came from if you have multiple topics with the same message type on it. For example, even if the message type is the same, you may want to handle the message differently based on which topic it came from.
Message consumer will now pass the topic to the per-message callbacks.
=> Message Consumer - Pass Topic in Callbacks

trellis/BUILD, trellis/core/test/test_timer.cpp, trellis/core/timer.hpp
* Fixes a race condition causing flaky unit test
* More granular cc_test definitions
* Using atomic bool for thread safety
=> Fix Race Condition in Timer Test

trellis/core/node.hpp, trellis/core/subscriber.hpp
This PR refactors `trellis::core::SubscriberImpl` such that it can be used as a generic dynamic subscriber (with `MSG_T = google::protobuf::Message`). Now `DynamicSubscriber` is no longer a direct alias of eCAL's `eCAL::protobuf::CDynamicSubscriber`. Instead it is an alias of `SubscriberImpl` specialized with `google::protobuf::Message`
This allows code reuse of `trellis::core::SubscriberImpl` and associated functionality, such as watchdog timeouts, for the case of dynamic subscribers.
=> Dynamic Subscriber Refactor

third_party/repositories.bzl
https://github.com/continental/ecal/releases/tag/v5.9.2
=> Update eCAL to v5.9.2

trellis/core/node.hpp, trellis/core/subscriber.hpp, trellis/core/test/test_pubsub.cpp
Adds support for specifying a maximum frequency to throttle the rate in which the subscriber may call the inbound message callback
=> Subscriber Callback Max Frequency (Rate Throttle)

trellis/core/subscriber.hpp
Took me a while to hunt down which units the variable was in. I figured I'd add it to the docstring / variable name.
=> Set max_frequency variables to max_frequency_hz

trellis/BUILD, trellis/core/test/test_time.cpp, trellis/core/time.hpp
Properly scales the time since epoch in seconds.
Adds a unit test to validate the fix.
=> trellis::core::TimePointToSeconds() scaling bugfix

trellis/examples/config.yml, trellis/examples/publisher/app.cpp, trellis/examples/service_client/app.cpp
Also includes a couple small fixes:
- off-by-one error on message ID for publisher
- stale if statement was masking timeout error check on service call
=> Examples - Add Initial Delay for Publish / Service Call

trellis/core/test/test_time.cpp, trellis/core/time.hpp
Adds Timepoint helpers for quickly accessing nanoseconds and milliseconds since epoch.
=> Add nano and milli seconds helpers for TimePoint

trellis/core/node.cpp, trellis/tools/trellis-cli/topic/topic_echo_main.cpp
Added a whitespace option to disable adding whitespace by default so that JSON output is single line only.
Added a verbose option to disable outputting non-essential output by default.
This makes it easy to pipe the output of topic echo to other programs that expect JSON only.
=> Trellis CLI Topic Echo Whitespace and Verbose Options

trellis/tools/trellis-cli/BUILD
This allows other workspaces which include trellis to be able to build the CLI target
=> CLI Remove Workspace Name Dependency from BUILD Dep

third_party/repositories.bzl
Use `Label()` so that other workspaces calling `trellis_deps()` can find the build file
=> Fix spdlog build file path

trellis/tools/trellis-cli/BUILD
I'm trying to depend on this target in a `filegroup` in my repo, but this isn't public visible.
=> Set visibility of trellis-cli to public

third_party/ecal.BUILD, trellis/tools/sys_client_cli/BUILD
Add ecal-sys-client-cli to //third_party/ecal.BUILD
I followed your paradigm by specifying all required files ( instead of globs), and removing the prefix `ecal_` from the targets.
=> Add ecal-sys-client-cli to //third_party/ecal.BUILD

trellis/core/message_consumer.hpp, trellis/core/test/test_message_consumer.cpp, trellis/examples/subscriber/app.cpp
Before this change, in cases where we are using MessageConsumer to receives the same message type on multiple topics, we couldn't differentiate between which topic was actually triggering the watchdog.
Now we simply supply the topic when the watchdog trips
=> Message Consumer Watchdog Callback API Update - Topic Name Argument

trellis/core/test/test_time.cpp, trellis/core/time.cpp, trellis/core/time.hpp
Adds an API to convert `time::TimePoint` values into system time, which is useful for reporting / logging.
=> TimePointToSystemTime() API

trellis/core/BUILD, trellis/core/logging.cpp, trellis/core/logging.hpp
This makes it easier for other libraries to depend on logging only. Also, the eCAL dependency is limited to the cpp file now.
=> Isolate logging to separate cc_library with cpp file

trellis/core/test/test_timer.cpp, trellis/core/timer.cpp, trellis/core/timer.hpp
There were cases where `Expired()` may return the wrong value for one shot timers. This PR fixes the logic to be more robust.
=> One Shot Timer Expired() logic fix

trellis/core/monitor_interface.cpp, trellis/core/proto_utils.hpp, trellis/core/test/BUILD, trellis/core/test/test_proto_utils.cpp, trellis/tools/trellis-cli/topic/topic_list_main.cpp
We have a notion of a "raw" topic associated with every topic as a way of advertising additional metadata to the monitoring layer.
Previously we would append "/raw" to every topic name. Now instead we prepend "/trellis/raw:" to better namespace the topic strings that are internal to trellis.
=> Cleanup 'raw' topic mechanism

trellis/core/node.hpp, trellis/core/publisher.hpp
eCAL has a zero-copy feature for publishers, which is meant for larger messages. This PR brings in support for that feature for Trellis publishers.
Here's more info: https://continental.github.io/ecal/_api/classeCAL_1_1CPublisher.html#_CPPv4N4eCAL10CPublisher17ShmEnableZeroCopyEb
=> Publisher Zero Copy Support

trellis/BUILD, trellis/core/BUILD, trellis/core/test/BUILD, trellis/network/BUILD
Following better practices and making cc_library rules much more granular. It has the benefit of avoiding circular dependencies. It also has the benefit of making Bazel more aware of the source code dependencies, and minimizes what gets rebuilt when source files are edited.
=> Cleanup cc_library dependencies
